name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.ts"
  pull_request:
    branches:
      - main
    paths:
      - "**.ts"

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: pnpm

      - name: Typecheck
        run: pnpm run typecheck
